### ISSUE TITLE
Original DC BIOS files.

### ISSUE THREAD

**Issue by jdwininger** [duckey77/Flycast-Core#1]
I assume the OpenEmu Flycast core uses the builtin HLE bios for emulation. If so is there any way to use a real DC BIOS in place of the HLE one?

**Comment by duckey77** [comment]
You have to manually place them into the BIOS direcoty under ~/Library/Appliation Support/OpenEmu/BIOS/

They should be named dc_boot.bin and dc_flash.bin

**Comment by jdwininger** [comment]
thank you bery much for the information.
